import { SortedData } from '../api/types/types';

export const SYNC_INTERVAL = 15000;

export const initialSortedData: SortedData = {
  tempCube: 0,
  tempCargi: 0,
  tempDef: 0,
  tempWater: 0,
  handWork: 0,
  errorHand: 0,
  handPower: 0,
  handPercent: 0.06,
  handTempSelect: 0,
  handTempGyst: 0.1,
  handWoterError: 0,
  handTempWoterError: 0,
  handLevelError: 0,
  handTempCubeError: 0,
  version: 0,
  handTen: 0,
  handK1: 0,
  handK2: 0,
  handK3: 0,
  handPin1: 0,
  handPin2: 0,
  selection: 0,
  selectionSpeed: 0.06,
  handSpeedTail: 0.06,
  handK4: 0,
  switchBody: 0,

  distAcceleration: 0,
  distPower: 0,
  distTempPower: 0,
  distTempStop: 0,
  distTempError: 0,
  distPowerBody: 0,
  distTimeBody: 0,
  distCubeHead: 0,
  distCubeSwitch: 0,

  rectAcceleration: 0,
  rectPower: 0,
  rectPowerBody: 0,
  rectTempPower: 0,
  rectTempStop: 0,
  rectTempHead: 0,
  rectGystHead: 0,
  rectTempBody: 0,
  rectGystBody: 0,
  rectPercentHead: 0, 
  rectPercentBody: 0,
  rectDecreaseTemp: 0,
  rectDecreaseSpeed: 0,
  rectTempError: 0,
  rectTimeStab: 0,
  rectCubeTail: 0,
  rectSpeedTail: 0,
  rectSpeedCarge: 0,
  rectDecreaseCycle: 0,
  rectCyclesNumber: 0,
  rectEndCycle: 0,
  rectPowerTail: 0,
  rectTimeBody: 0,
  rectSwitchTail: 0,
  rectSwitchCube: 0,
  rectSwitchCarge: 0,
  rectSelectCarge: 0,
  transitBody: 0,

  mashingPauses: 0,
  mashingHeat: 0,
  mashingHeatTemp: 0,
  mashingHeatPower: 0,
  mashingHeatTime: 0,
  mashingCool: 0, 
  mashingCoolTemp: 0, 
  mashingCoolGyst: 0,
  mashingTemp0: 0,
  mashingTemp1: 0,
  mashingTemp2: 0,
  mashingTemp3: 0,
  mashingTemp4: 0,
  mashingTemp5: 0,
  mashingTemp6: 0,
  mashingTemp7: 0,
  mashingTemp8: 0,
  mashingTemp9: 0,
  mashingGyst0: 0,
  mashingGyst1: 0,
  mashingGyst2: 0,
  mashingGyst3: 0,
  mashingGyst4: 0,
  mashingGyst5: 0,
  mashingGyst6: 0,
  mashingGyst7: 0,
  mashingGyst8: 0,
  mashingGyst9: 0,

  mashingTime0: 0,
  mashingTime1: 0,
  mashingTime2: 0,
  mashingTime3: 0,
  mashingTime4: 0,
  mashingTime5: 0,
  mashingTime6: 0,
  mashingTime7: 0,
  mashingTime8: 0,
  mashingTime9: 0,

};
