export type SortedData = {
  tempCube: number;
  tempCargi: number;
  tempDef: number;
  tempWater: number;
  handWork: number;
  errorHand: number;
  handPower: number;
  handPercent: number;
  handTempSelect: number;
  handTempGyst: number;
  handWaterError: number;
  handTempWaterError: number;
  handLevelError: number;
  handTempCubeError: number;
  version: number;
  handTen: number;
  handK1: number;
  handK2: number;
  handK3: number;
  handPin1: number;
  handPin2: number;
  selection: number;
  selectionSpeed: number;
  handSpeedTail: number;
  handK4: number;
  switchBody: number;
};
