export type SortedData = {
  tempCube: number;
  tempCargi: number;
  tempDef: number;
  tempWater: number;
  handWork: number;
  errorHand: number;
  handPower: number;
  handPercent: number;
  handTempSelect: number;
  handTempGyst: number;
  handWoterError: number;
  handTempWoterError: number;
  handLevelError: number;
  handTempCubeError: number;
  version: number;
  handTen: number;
  handK1: number;
  handK2: number;
  handK3: number;
  handPin1: number;
  handPin2: number;
  selection: number;
  selectionSpeed: number;
  handSpeedTail: number;
  handK4: number;
  switchBody: number;

  distAcceleration: number,
  distPower: number,
  distTempPower: number,
  distTempStop: number,
  distTempError: number,
  distPowerBody: number,
  distTimeBody: number,
  distCubeHead: number,
  distCubeSwitch: number,
  
  rectAcceleration: number,
  rectPower: number,
  rectPowerBody: number,
  rectTempPower: number,
  rectTempStop: number,
  rectTempHead: number,
  rectGystHead: number,
  rectTempBody: number,
  rectGystBody: number,
  rectPercentHead: number, 
  rectPercentBody: number,
  rectDecreaseTemp: number,
  rectDecreaseSpeed: number,
  rectTempError: number,
  rectTimeStab: number,
  rectCubeTail: number,
  rectSpeedTail: number,
  rectSpeedCarge: number,
  rectDecreaseCycle: number,
  rectCyclesNumber: number,
  rectEndCycle: number,
  rectPowerTail: number,
  rectTimeBody: number,
  rectSwitchTail: number,
  rectSwitchCube: number,
  rectSwitchCarge: number,
  rectSelectCarge: number,
  transitBody: number,

  mashingPauses: number,
  mashingHeat: number;
  mashingHeatTemp: number;
  mashingHeatPower: number;
  mashingHeatTime: number;
  mashingCool: number; 
  mashingCoolTemp: number; 
  mashingCoolGyst: number;
  mashingTemp0: number;
  mashingTemp1: number;
  mashingTemp2: number;
  mashingTemp3: number;
  mashingTemp4: number;
  mashingTemp5: number;
  mashingTemp6: number;
  mashingTemp7: number;
  mashingTemp8: number;
  mashingTemp9: number;
  mashingGyst0: number; 
  mashingGyst1: number; 
  mashingGyst2: number; 
  mashingGyst3: number; 
  mashingGyst4: number; 
  mashingGyst5: number; 
  mashingGyst6: number; 
  mashingGyst7: number; 
  mashingGyst8: number; 
  mashingGyst9: number;

  mashingTime0: number;
  mashingTime1: number;
  mashingTime2: number;
  mashingTime3: number;
  mashingTime4: number;
  mashingTime5: number;
  mashingTime6: number;
  mashingTime7: number;
  mashingTime8: number;
  mashingTime9: number;

};
